# Generated by Django 3.0.7 on 2020-08-30 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload from your device', null=True, upload_to='static/moodboard/images')),
                ('url_img', models.CharField(blank=True, default='', help_text='Or insert a link to image', max_length=256)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TheMoodboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=128)),
                ('isPrivate', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('share_url', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('nsfw', models.BooleanField(blank=True, default=False, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('picsContained', models.ManyToManyField(blank=True, to='Moodboard.Img')),
                ('tags', models.ManyToManyField(blank=True, to='Moodboard.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='img',
            name='moodboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Moodboard.TheMoodboard'),
        ),
    ]
